### ISSUE TITLE
How to properly embed gorackhd in another project?

### ISSUE THREAD

**Issue by codenrhoden** [emccode/gorackhd#11]
My question here is stemming from #10.  when working on github.com/codenrhoden/rackhdcli, I had originally started by working with `gorackhd` directly.  Because of that, I had previously `go install`'d it.

To use `gorackhd`, you have to `go install` it, then do a `make` to generate the clients with `go-swagger`.  When you run `make`, `gorackhd` uses glide to grab its dependencies and throw them in `gorackhd/vendor`.

At first I went down a path that let me to #10, whereby I was no longer using Glide in my project and was counting on having previously `go install`'d `gorackhd`.  I had forgotten how I got there, and @clintonskitson pointed out that was the wrong way to do things. I do need to use Glide and have `gorackhd` in there as my dependency.

However, now I'm stuck on what to do next. If I use Glide to install `gorackhd`, it is not going to run `make` for me. I'd still have to run `make` manually (or add it to a make in `rackhdcli`, which seems less than ideal). In the end, I'm not seeing how I can ever do `go install rackhdcli` and get something working as long as that `make` step is in there.

On a side note, if I go into my resulting `vendor`'d copy of `gorackhd` and run `make`, I still end up with a second `vendor` directory and end up with mis-matched types. But I think this is an additional result of the `make` process.

Just for clarity, here is my glide.yaml:

```
package: github.com/codenrhoden/rackhdcli
import:
- package: github.com/emccode/gorackhd
  subpackages:
  - client
- package: github.com/emccode/gorackhd-redfish
  subpackages:
  - client
- package: github.com/spf13/cobra
- package: github.com/spf13/viper
```

Am I doing this completely wrong?
